#pragma once

#include <Arduino.h>

#define MOTOR_STEP_PIN 22
#define MOTOR_DIR_PIN 23
#define MOTOR_ENABLE_PIN 21
#define MOTOR_ACCELERATION_STEPS 2000
#define MIN_STEP_INTERVAL_US 200

#define LIGHT_SENSOR_PIN 4

#define FORCE_SENSOR_RIGHT_PIN 32
#define FORCE_SENSOR_LEFT_PIN 33
#define MAGNET_RIGHT_PIN 18
#define MAGNET_LEFT_PIN 19

#ifndef APPARATUS_SERIAL_BAUD
#define APPARATUS_SERIAL_BAUD 921600
#endif

#ifndef APPARATUS_PC_COMPAT_MODE
#define APPARATUS_PC_COMPAT_MODE 1
#endif

#ifndef PC_SERIAL_LOG_ENABLED
#if APPARATUS_PC_COMPAT_MODE
#define PC_SERIAL_LOG_ENABLED 0
#else
#define PC_SERIAL_LOG_ENABLED 1
#endif
#endif

#if PC_SERIAL_LOG_ENABLED
#define PC_LOG_PRINT(...) Serial.print(__VA_ARGS__)
#define PC_LOG_PRINTLN(...) Serial.println(__VA_ARGS__)
#define PC_LOG_PRINTF(...) Serial.printf(__VA_ARGS__)
#else
#define PC_LOG_PRINT(...)
#define PC_LOG_PRINTLN(...)
#define PC_LOG_PRINTF(...)
#endif

#ifndef FORCE_TARE_ENABLED
#define FORCE_TARE_ENABLED 1
#endif

#ifndef FORCE_TARE_AT_BOOT
#define FORCE_TARE_AT_BOOT 1
#endif

#ifndef FORCE_TARE_ON_START
#define FORCE_TARE_ON_START 0
#endif

#ifndef FORCE_DEBUG_LOG
#define FORCE_DEBUG_LOG 0
#endif

#ifndef FORCE_MAX_HZ_ONE_CHANNEL
#define FORCE_MAX_HZ_ONE_CHANNEL 250
#endif

#ifndef FORCE_MAX_HZ_TWO_CHANNELS_PER_CH
#define FORCE_MAX_HZ_TWO_CHANNELS_PER_CH 125
#endif

#define FORCE_BACKEND_INTERNAL_CONTINUOUS 1
#define FORCE_BACKEND_ADS1115 2

#ifndef FORCE_BACKEND
#define FORCE_BACKEND FORCE_BACKEND_ADS1115
#endif

#ifndef FORCE_SERVICE_TASK_CORE
#define FORCE_SERVICE_TASK_CORE 0
#endif

#ifndef FORCE_SERVICE_TASK_PRIORITY
#define FORCE_SERVICE_TASK_PRIORITY 1
#endif

#ifndef FORCE_SERVICE_TASK_STACK_WORDS
#define FORCE_SERVICE_TASK_STACK_WORDS 4096
#endif

#ifndef FORCE_SERVICE_IDLE_DELAY_MS
#define FORCE_SERVICE_IDLE_DELAY_MS 5
#endif

#ifndef FORCE_SERVICE_RETRY_DELAY_MS
#define FORCE_SERVICE_RETRY_DELAY_MS 500
#endif
